#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed May 12 19:34:35 2021

@author: jonborunda
"""


#IMPORT PACKAGES

import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

df1 = pd.read_csv('sample.csv')
print(df1.head())
print(df1.dtypes)


#DATA CLEANING

df1.dropna(how='any',axis=0)
df1.dropna()

del df1['product_id']
del df1['category_id']
del df1['user_id']
del df1['event_time']
del df1['user_session']

nan_value = float("NaN")
df1.replace("", nan_value, inplace=True)
df1.dropna(inplace=True)
print(df1.head())

category = df1['category_code'].str.split(".", n = 2, expand = True)
df1['category']= category[0]
df1['subcategory']= category[1]
df1['subtype']= category[2]
df1.drop(columns =['category_code'], inplace = True)
df1.dropna(inplace = True)
print(df1.head())


#STATISTICS

print(df1[["event_type", "price"]].groupby("event_type").describe())
print(df1[["brand", "price"]].groupby("brand").median())
print(df1[["brand", "price"]].groupby("brand").mean())
print(df1[["brand", "price"]].groupby("brand").std(ddof=0))


#VISUALIZATIONS

#NOTE: Visualizations should be executed individually

#Bar Chart
df1['brand'].value_counts()[:10].plot(kind='barh')
plt.xlabel("Count")
plt.ylabel("Brand")
plt.title("Top 10 Brands with Activity")

#Scatter Plot
sns.relplot(data=df1, x=df1['price'], y=df1['category'], hue="event_type", style="event_type")

#Violin Plot
sns.set_style('whitegrid')
sns.violinplot(x='category',y='price', data=df1, figsize=(1000,1000))
plt.show()




